'use strict';

const COUNTRY_TLDS = [
  { code: 'AF', country: 'Afghanistan', tlds: ['af'] },
  { code: 'AL', country: 'Albania', tlds: ['al'] },
  { code: 'DZ', country: 'Algeria', tlds: ['dz'] },
  { code: 'AD', country: 'Andorra', tlds: ['ad'] },
  { code: 'AO', country: 'Angola', tlds: ['ao'] },
  { code: 'AG', country: 'Antigua and Barbuda', tlds: ['ag'] },
  { code: 'AR', country: 'Argentina', tlds: ['ar'] },
  { code: 'AM', country: 'Armenia', tlds: ['am'] },
  { code: 'AU', country: 'Australia', tlds: ['au'] },
  { code: 'AT', country: 'Austria', tlds: ['at'] },
  { code: 'AZ', country: 'Azerbaijan', tlds: ['az'] },
  { code: 'BS', country: 'Bahamas', tlds: ['bs'] },
  { code: 'BH', country: 'Bahrain', tlds: ['bh'] },
  { code: 'BD', country: 'Bangladesh', tlds: ['bd'] },
  { code: 'BB', country: 'Barbados', tlds: ['bb'] },
  { code: 'BY', country: 'Belarus', tlds: ['by'] },
  { code: 'BE', country: 'Belgium', tlds: ['be'] },
  { code: 'BZ', country: 'Belize', tlds: ['bz'] },
  { code: 'BJ', country: 'Benin', tlds: ['bj'] },
  { code: 'BT', country: 'Bhutan', tlds: ['bt'] },
  { code: 'BO', country: 'Bolivia', tlds: ['bo'] },
  { code: 'BA', country: 'Bosnia and Herzegovina', tlds: ['ba'] },
  { code: 'BW', country: 'Botswana', tlds: ['bw'] },
  { code: 'BR', country: 'Brazil', tlds: ['br'] },
  { code: 'BN', country: 'Brunei', tlds: ['bn'] },
  { code: 'BG', country: 'Bulgaria', tlds: ['bg'] },
  { code: 'BF', country: 'Burkina Faso', tlds: ['bf'] },
  { code: 'BI', country: 'Burundi', tlds: ['bi'] },
  { code: 'KH', country: 'Cambodia', tlds: ['kh'] },
  { code: 'CM', country: 'Cameroon', tlds: ['cm'] },
  { code: 'CA', country: 'Canada', tlds: ['ca'] },
  { code: 'CV', country: 'Cape Verde', tlds: ['cv'] },
  { code: 'CF', country: 'Central African Republic', tlds: ['cf'] },
  { code: 'TD', country: 'Chad', tlds: ['td'] },
  { code: 'CL', country: 'Chile', tlds: ['cl'] },
  { code: 'CN', country: 'China', tlds: ['cn'] },
  { code: 'CO', country: 'Colombia', tlds: ['co'] },
  { code: 'KM', country: 'Comoros', tlds: ['km'] },
  { code: 'CG', country: 'Republic of the Congo', tlds: ['cg'] },
  { code: 'CD', country: 'Democratic Republic of the Congo', tlds: ['cd'] },
  { code: 'CR', country: 'Costa Rica', tlds: ['cr'] },
  { code: 'CI', country: 'Côte d’Ivoire', tlds: ['ci'] },
  { code: 'HR', country: 'Croatia', tlds: ['hr'] },
  { code: 'CU', country: 'Cuba', tlds: ['cu'] },
  { code: 'CY', country: 'Cyprus', tlds: ['cy'] },
  { code: 'CZ', country: 'Czechia', tlds: ['cz'] },
  { code: 'DK', country: 'Denmark', tlds: ['dk'] },
  { code: 'DJ', country: 'Djibouti', tlds: ['dj'] },
  { code: 'DM', country: 'Dominica', tlds: ['dm'] },
  { code: 'DO', country: 'Dominican Republic', tlds: ['do'] },
  { code: 'EC', country: 'Ecuador', tlds: ['ec'] },
  { code: 'EG', country: 'Egypt', tlds: ['eg'] },
  { code: 'SV', country: 'El Salvador', tlds: ['sv'] },
  { code: 'GQ', country: 'Equatorial Guinea', tlds: ['gq'] },
  { code: 'ER', country: 'Eritrea', tlds: ['er'] },
  { code: 'EE', country: 'Estonia', tlds: ['ee'] },
  { code: 'SZ', country: 'Eswatini', tlds: ['sz'] },
  { code: 'ET', country: 'Ethiopia', tlds: ['et'] },
  { code: 'FJ', country: 'Fiji', tlds: ['fj'] },
  { code: 'FI', country: 'Finland', tlds: ['fi'] },
  { code: 'FR', country: 'France', tlds: ['fr'] },
  { code: 'GA', country: 'Gabon', tlds: ['ga'] },
  { code: 'GM', country: 'Gambia', tlds: ['gm'] },
  { code: 'GE', country: 'Georgia', tlds: ['ge'] },
  { code: 'DE', country: 'Germany', tlds: ['de'] },
  { code: 'GH', country: 'Ghana', tlds: ['gh'] },
  { code: 'GR', country: 'Greece', tlds: ['gr'] },
  { code: 'GD', country: 'Grenada', tlds: ['gd'] },
  { code: 'GT', country: 'Guatemala', tlds: ['gt'] },
  { code: 'GN', country: 'Guinea', tlds: ['gn'] },
  { code: 'GW', country: 'Guinea-Bissau', tlds: ['gw'] },
  { code: 'GY', country: 'Guyana', tlds: ['gy'] },
  { code: 'HT', country: 'Haiti', tlds: ['ht'] },
  { code: 'HN', country: 'Honduras', tlds: ['hn'] },
  { code: 'HU', country: 'Hungary', tlds: ['hu'] },
  { code: 'IS', country: 'Iceland', tlds: ['is'] },
  { code: 'IN', country: 'India', tlds: ['in'] },
  { code: 'ID', country: 'Indonesia', tlds: ['id'] },
  { code: 'IR', country: 'Iran', tlds: ['ir'] },
  { code: 'IQ', country: 'Iraq', tlds: ['iq'] },
  { code: 'IE', country: 'Ireland', tlds: ['ie'] },
  { code: 'IL', country: 'Israel', tlds: ['il'] },
  { code: 'IT', country: 'Italy', tlds: ['it'] },
  { code: 'JM', country: 'Jamaica', tlds: ['jm'] },
  { code: 'JP', country: 'Japan', tlds: ['jp'] },
  { code: 'JO', country: 'Jordan', tlds: ['jo'] },
  { code: 'KZ', country: 'Kazakhstan', tlds: ['kz'] },
  { code: 'KE', country: 'Kenya', tlds: ['ke'] },
  { code: 'KI', country: 'Kiribati', tlds: ['ki'] },
  { code: 'KP', country: 'North Korea', tlds: ['kp'] },
  { code: 'KR', country: 'South Korea', tlds: ['kr'] },
  { code: 'KW', country: 'Kuwait', tlds: ['kw'] },
  { code: 'KG', country: 'Kyrgyzstan', tlds: ['kg'] },
  { code: 'LA', country: 'Laos', tlds: ['la'] },
  { code: 'LV', country: 'Latvia', tlds: ['lv'] },
  { code: 'LB', country: 'Lebanon', tlds: ['lb'] },
  { code: 'LS', country: 'Lesotho', tlds: ['ls'] },
  { code: 'LR', country: 'Liberia', tlds: ['lr'] },
  { code: 'LY', country: 'Libya', tlds: ['ly'] },
  { code: 'LI', country: 'Liechtenstein', tlds: ['li'] },
  { code: 'LT', country: 'Lithuania', tlds: ['lt'] },
  { code: 'LU', country: 'Luxembourg', tlds: ['lu'] },
  { code: 'MG', country: 'Madagascar', tlds: ['mg'] },
  { code: 'MW', country: 'Malawi', tlds: ['mw'] },
  { code: 'MY', country: 'Malaysia', tlds: ['my'] },
  { code: 'MV', country: 'Maldives', tlds: ['mv'] },
  { code: 'ML', country: 'Mali', tlds: ['ml'] },
  { code: 'MT', country: 'Malta', tlds: ['mt'] },
  { code: 'MH', country: 'Marshall Islands', tlds: ['mh'] },
  { code: 'MR', country: 'Mauritania', tlds: ['mr'] },
  { code: 'MU', country: 'Mauritius', tlds: ['mu'] },
  { code: 'MX', country: 'Mexico', tlds: ['mx'] },
  { code: 'FM', country: 'Micronesia', tlds: ['fm'] },
  { code: 'MD', country: 'Moldova', tlds: ['md'] },
  { code: 'MC', country: 'Monaco', tlds: ['mc'] },
  { code: 'MN', country: 'Mongolia', tlds: ['mn'] },
  { code: 'ME', country: 'Montenegro', tlds: ['me'] },
  { code: 'MA', country: 'Morocco', tlds: ['ma'] },
  { code: 'MZ', country: 'Mozambique', tlds: ['mz'] },
  { code: 'MM', country: 'Myanmar', tlds: ['mm'] },
  { code: 'NA', country: 'Namibia', tlds: ['na'] },
  { code: 'NR', country: 'Nauru', tlds: ['nr'] },
  { code: 'NP', country: 'Nepal', tlds: ['np'] },
  { code: 'NL', country: 'Netherlands', tlds: ['nl'] },
  { code: 'NZ', country: 'New Zealand', tlds: ['nz'] },
  { code: 'NI', country: 'Nicaragua', tlds: ['ni'] },
  { code: 'NE', country: 'Niger', tlds: ['ne'] },
  { code: 'NG', country: 'Nigeria', tlds: ['ng'] },
  { code: 'MK', country: 'North Macedonia', tlds: ['mk'] },
  { code: 'NO', country: 'Norway', tlds: ['no'] },
  { code: 'OM', country: 'Oman', tlds: ['om'] },
  { code: 'PK', country: 'Pakistan', tlds: ['pk', 'com.pk', 'net.pk', 'org.pk'] },
  { code: 'PW', country: 'Palau', tlds: ['pw'] },
  { code: 'PS', country: 'Palestine', tlds: ['ps'] },
  { code: 'PA', country: 'Panama', tlds: ['pa'] },
  { code: 'PG', country: 'Papua New Guinea', tlds: ['pg'] },
  { code: 'PY', country: 'Paraguay', tlds: ['py'] },
  { code: 'PE', country: 'Peru', tlds: ['pe'] },
  { code: 'PH', country: 'Philippines', tlds: ['ph'] },
  { code: 'PL', country: 'Poland', tlds: ['pl'] },
  { code: 'PT', country: 'Portugal', tlds: ['pt'] },
  { code: 'QA', country: 'Qatar', tlds: ['qa'] },
  { code: 'RO', country: 'Romania', tlds: ['ro'] },
  { code: 'RU', country: 'Russia', tlds: ['ru', 'рф'] },
  { code: 'RW', country: 'Rwanda', tlds: ['rw'] },
  { code: 'KN', country: 'Saint Kitts and Nevis', tlds: ['kn'] },
  { code: 'LC', country: 'Saint Lucia', tlds: ['lc'] },
  { code: 'VC', country: 'Saint Vincent and the Grenadines', tlds: ['vc'] },
  { code: 'WS', country: 'Samoa', tlds: ['ws'] },
  { code: 'SM', country: 'San Marino', tlds: ['sm'] },
  { code: 'ST', country: 'São Tomé and Príncipe', tlds: ['st'] },
  { code: 'SA', country: 'Saudi Arabia', tlds: ['sa'] },
  { code: 'SN', country: 'Senegal', tlds: ['sn'] },
  { code: 'RS', country: 'Serbia', tlds: ['rs'] },
  { code: 'SC', country: 'Seychelles', tlds: ['sc'] },
  { code: 'SL', country: 'Sierra Leone', tlds: ['sl'] },
  { code: 'SG', country: 'Singapore', tlds: ['sg'] },
  { code: 'SK', country: 'Slovakia', tlds: ['sk'] },
  { code: 'SI', country: 'Slovenia', tlds: ['si'] },
  { code: 'SB', country: 'Solomon Islands', tlds: ['sb'] },
  { code: 'SO', country: 'Somalia', tlds: ['so'] },
  { code: 'ZA', country: 'South Africa', tlds: ['za'] },
  { code: 'SS', country: 'South Sudan', tlds: ['ss'] },
  { code: 'ES', country: 'Spain', tlds: ['es'] },
  { code: 'LK', country: 'Sri Lanka', tlds: ['lk'] },
  { code: 'SD', country: 'Sudan', tlds: ['sd'] },
  { code: 'SR', country: 'Suriname', tlds: ['sr'] },
  { code: 'SE', country: 'Sweden', tlds: ['se'] },
  { code: 'CH', country: 'Switzerland', tlds: ['ch'] },
  { code: 'SY', country: 'Syria', tlds: ['sy'] },
  { code: 'TW', country: 'Taiwan', tlds: ['tw'] },
  { code: 'TJ', country: 'Tajikistan', tlds: ['tj'] },
  { code: 'TZ', country: 'Tanzania', tlds: ['tz'] },
  { code: 'TH', country: 'Thailand', tlds: ['th'] },
  { code: 'TL', country: 'Timor-Leste', tlds: ['tl'] },
  { code: 'TG', country: 'Togo', tlds: ['tg'] },
  { code: 'TO', country: 'Tonga', tlds: ['to'] },
  { code: 'TT', country: 'Trinidad and Tobago', tlds: ['tt'] },
  { code: 'TN', country: 'Tunisia', tlds: ['tn'] },
  { code: 'TR', country: 'Turkey', tlds: ['tr'] },
  { code: 'TM', country: 'Turkmenistan', tlds: ['tm'] },
  { code: 'TV', country: 'Tuvalu', tlds: ['tv'] },
  { code: 'UG', country: 'Uganda', tlds: ['ug'] },
  { code: 'UA', country: 'Ukraine', tlds: ['ua'] },
  { code: 'AE', country: 'United Arab Emirates', tlds: ['ae'] },
  { code: 'GB', country: 'United Kingdom', tlds: ['uk', 'co.uk', 'org.uk'] },
  { code: 'US', country: 'United States', tlds: ['us'] },
  { code: 'UY', country: 'Uruguay', tlds: ['uy'] },
  { code: 'UZ', country: 'Uzbekistan', tlds: ['uz'] },
  { code: 'VU', country: 'Vanuatu', tlds: ['vu'] },
  { code: 'VA', country: 'Vatican City', tlds: ['va'] },
  { code: 'VE', country: 'Venezuela', tlds: ['ve'] },
  { code: 'VN', country: 'Vietnam', tlds: ['vn'] },
  { code: 'YE', country: 'Yemen', tlds: ['ye'] },
  { code: 'ZM', country: 'Zambia', tlds: ['zm'] },
  { code: 'ZW', country: 'Zimbabwe', tlds: ['zw'] }
];

const GENERIC_TLDS = [
  'com', 'net', 'org', 'info', 'biz', 'name', 'pro',
  'io', 'ai', 'app', 'dev', 'cloud', 'tech', 'online',
  'site', 'store', 'shop', 'agency', 'digital', 'media',
  'website', 'solutions', 'software', 'company', 'systems',
  'network', 'services', 'email', 'live', 'space', 'world',
  'today', 'xyz', 'club', 'social', 'one', 'life', 'work',
  'business', 'marketing', 'academy', 'education', 'school',
  'design', 'studio', 'art', 'blog', 'news', 'travel',
  'coffee', 'cafe', 'games', 'music', 'video', 'photography'
];

module.exports = {
  COUNTRY_TLDS,
  GENERIC_TLDS
};
